name: pikanto
description: 'Record weight, prepare waybill order, and route approval for delivery.'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  english_words: ^4.0.0
  provider: ^6.0.0
  image_picker: ^0.8.4+2
  file_picker: ^8.3.2
  path_provider: ^2.0.8
  path: ^1.8.0
  dropdown_search: ^5.0.3
  http: ^0.13.3
  loading_animation_widget: ^1.2.1
  flutter_libserialport: ^0.4.0
  libserialport: ^0.3.0+1
  connectivity_plus: ^3.0.2
  intl: ^0.18.0
  printing: ^5.13.2
  pdf: ^3.10.1
  web_socket_channel: ^2.1.0
  flutter_local_notifications: ^14.0.0
  socket_io_client: ^2.0.0
  shared_preferences: ^2.0.0
  win32: ^5.5.4
  ffi: ^2.1.3
  windows_notification: ^1.3.0
  window_manager: ^0.4.3
  archive: ^3.3.5  # For extracting zip files
  process_run: ^0.13.0  # For running system commands (to restart app)
  version: ^3.0.2  # For comparing app versions
  syncfusion_flutter_pdfviewer: ^20.4.54
  open_filex: ^4.7.0
  flutter_widget_from_html: ^0.16.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/fonts/roboto/
    #- assets/images/
    #- assets/icons/
    #- assets/fonts/
    #- assets/translations/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpeg"