"""empty message

Revision ID: 262db18d21a7
Revises: a2642aeeedeb
Create Date: 2024-09-03 14:05:12.456843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262db18d21a7'
down_revision = 'a2642aeeedeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_approver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_waybill_log_primary_approver', 'users', ['primary_approver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waybill_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_waybill_log_primary_approver', type_='foreignkey')
        batch_op.drop_column('primary_approver_id')

    # ### end Alembic commands ###
