"""empty message

Revision ID: 632d5e02a635
Revises: 81a490652fc9
Create Date: 2024-09-18 20:46:09.710004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632d5e02a635'
down_revision = '81a490652fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('config', sa.String(length=6550), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_settings_company_id', ['company_id'])
        batch_op.drop_column('device_name')
        batch_op.drop_column('bytesize')
        batch_op.drop_column('number_of_approver')
        batch_op.drop_column('reg')
        batch_op.drop_column('parity')
        batch_op.drop_column('stopbits')
        batch_op.drop_column('unit')
        batch_op.drop_column('port')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('stopbits', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('parity', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('reg', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('number_of_approver', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bytesize', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('device_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('uq_settings_company_id', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('config')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
