"""empty message

Revision ID: 81a490652fc9
Revises: 94b06fcc350a
Create Date: 2024-09-11 19:03:43.074889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a490652fc9'
down_revision = '94b06fcc350a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_scope', sa.String(length=50), default='all'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('message_scope')

    # ### end Alembic commands ###
