"""empty message

Revision ID: 94b06fcc350a
Revises: df14f745af7d
Create Date: 2024-09-08 14:47:23.829661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b06fcc350a'
down_revision = 'df14f745af7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
