"""empty message

Revision ID: 98f80b311a2f
Revises: 9513638c369f
Create Date: 2024-09-08 14:25:08.519410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f80b311a2f'
down_revision = '9513638c369f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
