"""Added new tables

Revision ID: a2642aeeedeb
Revises: 0480cf37a8d6
Create Date: 2024-09-02 14:59:18.084988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2642aeeedeb'
down_revision = '0480cf37a8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
