"""empty message

Revision ID: df14f745af7d
Revises: 98f80b311a2f
Create Date: 2024-09-08 14:44:01.144134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df14f745af7d'
down_revision = '98f80b311a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
